apiVersion: v1
kind: Service
metadata:
  name: headless-chromium
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 9222
      targetPort: remote-debug
      protocol: TCP
      name: remote-debug
  selector:
    app: headless-chromium
