apiVersion: v1
kind: Service
metadata:
  name: openclaw-chromedriver
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 9515
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: openclaw-chromedriver
