apiVersion: v1
kind: Service
metadata:
  name: chromium
  namespace: default
spec:
  ports:
    - name: http
      port: 3000
      targetPort: http
      protocol: TCP
    - name: debug
      port: 9222
      targetPort: debug
      protocol: TCP
  selector:
    app: chromium
